crawler/crawler/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'crawler.views.home', name='home'),
    # url(r'^crawler/', include('crawler.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('spider.urls',namespace='spider')),
    url(r'^account/',include('account.urls',namespace='account')),
)
urlpatterns += patterns((''),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': '/home/gs/blog/static'}
    ),
    (r'^comments/', include('django.contrib.comments.urls')),
)

crawler/spider/urls.py
__author__ = 'seraph'
from django.conf.urls import patterns, url
from spider import views

urlpatterns = patterns('',
    url(r'^$',views.listing, name='index'),
    url(r'^v1/list/$',views.listing_ajax, name='index_ajax'),
    #url(r'regist/$',views.regist,name='regist'),
    #url(r'login/$',views.login,name='login'),
    #url(r'logout/$',views.logout,name='logout'),
    url(r'^(?P<car_cate>[a-z]+)/$',views.listing, name='cate'),
    url(r'^(?P<car_id>\d+)/$',views.detail,name='detail'),
    url(r'^(?P<id>\d+)/commentshow/$', views.details_show_comment, name='showcomment'),

)

crawler/templates/base.html
<!DOCTYPE html>
{% load comments %}
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="just for study">
    <meta name="author" content="max">
    <title>{% block title %}{% endblock %}</title>
    
    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <link href="/static/css/bootstrap-theme.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/static/css/offcanvas.css" rel="stylesheet">
    <link href="/static/css/common.css" rel="stylesheet">
    <!-- <link href="/static/css/sticky-footer.css" rel="stylesheet"> -->

    <link rel="icon" href="/static/fonts/favicon64.png" />

</head>
<body>

<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'spider:index' %}">多可笑</a>
    </div>
    <div class="scollapse navbar-collapse">
      <ul class="nav navbar-nav">
        {% if not site %}
        <li id="car"><a href="{% url 'spider:index' %}car">汽车</a></li>
        <li id="boat"><a href="{% url 'spider:index' %}boat">游艇</a></li>
        <li id="plane"><a href="{% url 'spider:index' %}plane">飞机</a></li>
        <li id="motorbike"><a href="{% url 'spider:index' %}motorbike">摩托车</a></li>
        <li id="house"><a href="{% url 'spider:index' %}house">豪宅</a></li>
        <li id="food"><a href="{% url 'spider:index' %}food">美食</a></li>
        {% else %}
        <li id="car"><a href="{% url 'spider:index' %}car/?site={{ site }}">汽车</a></li>
        <li id="boat"><a href="{% url 'spider:index' %}boat/?site={{ site }}">游艇</a></li>
        <li id="plane"><a href="{% url 'spider:index' %}plane/?site={{ site }}">飞机</a></li>
        <li id="motorbike"><a href="{% url 'spider:index' %}motorbike/?site={{ site }}">摩托车</a></li>
        <li id="house"><a href="{% url 'spider:index' %}house/?site={{ site }}">豪宅</a></li>
        <li id="food"><a href="{% url 'spider:index' %}food/?site={{ site }}">美食</a></li>
        {% endif %}
        <form action="{% url 'spider:index' %}" method="get" class="form-search pull-right" id="search">
            <li>
            <input type="text" class="input-medium search-query" name="query">
            <button type="submit" class="btn btn-small">搜索</button>
            </li>
        </form>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li><a href="/account/logout/">{{ user.username }}</a></li>
        {% else %}
        <li>
        <a href="#" data-toggle="modal" data-target="#login">登录</a>
        </li>
        <li>
        <a href="#" data-toggle="modal" data-target="#reg">注册</a>
        </li>
        {% endif %}
      </ul>
    </div><!-- /.nav-collapse -->
    
  </div><!-- /.container -->
</div>


<!-- Modal 登录 -->
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">登录</h4>
      </div>
      <div class="modal-body">
          <form id="loginform" method="post" enctype="multipart/form-data" class="form-signin" role="form">
            <span class="label label-warning"></span>
            {% csrf_token %}
            <input type="text" class="form-control" placeholder="请输入邮箱地址" required="" autofocus="" name="username">
            <input type="password" class="form-control" placeholder="请输入您的密码" required="" name="password">
            <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
          </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<!-- Modal 注册 -->
<div class="modal fade" id="reg" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">注册</h4>
      </div>
      <div class="modal-body">
        <form id="regform" method="post" enctype="multipart/form-data" class="form-signin" role="form">
        <span class="label label-warning"></span>
        {% csrf_token %}
        <input type="text" class="form-control" placeholder="请输入您的昵称" required="" autofocus="" name="screen_name">
        <input type="text" class="form-control" placeholder="请输入邮箱地址" required="" autofocus="" name="username">
        <input type="password" class="form-control" placeholder="请输入您的密码" required="" name="password">
        <button class="btn btn-lg btn-primary btn-block" type="submit">注册</button>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="container">

<div class="main">
  <div class="row row-offcanvas row-offcanvas-right">

    <div class="col-xs-12 col-sm-9">
        {% block content %}
        {% endblock %}
        {% block comments %}
        {% endblock %} 
    </div><!--/span-->

    <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
        {% block website %}
        {% endblock %}
      <div class="alert alert-warning">
        注意：<br/>本网站所有数据皆为抓取所得，纯为练手之用
      </div>
      <hr>

      <table class="table table-striped table-hover">
        {% block recent %}
            <thead><td><h3>最近更新</td></thead>
            <tbody>
            {% for i in car_rencent %}

            <tr><td><a class="text-warning" href="{% url 'spider:detail' i.id %}">{{ i.car_title }}</a></td></tr>
            {% endfor %}
            </tbody>
        {% endblock %}
        </table>
        <hr>
        <div class="alert alert-warning">
          联系方式:<br/>seraph0017@hotmail.com
        </div>
    </div><!--/span-->
  </div><!--/row-->

  <hr>
</div>
  <footer>
    <p>© max 2013</p>
  </footer>

</div>




<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/static/js/jquery.js"></script>
<script src="/static/js/bootstrap.js"></script>
<script src="/static/js/offcanvas.js"></script>
{% block script %}
{% endblock %}
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-46056132-1', 'max-xn.com');
    ga('send', 'pageview');

</script>

</body>
</html>