crawler/crawler/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'crawler.views.home', name='home'),
    # url(r'^crawler/', include('crawler.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('spider.urls',namespace='spider')),
    url(r'^account/',include('account.urls',namespace='account')),
)
urlpatterns += patterns((''),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': '/home/gs/blog/static'}
    ),
    (r'^comments/', include('django.contrib.comments.urls')),
)

crawler/spider/urls.py
__author__ = 'seraph'
from django.conf.urls import patterns, url
from spider import views

urlpatterns = patterns('',
    url(r'^$',views.listing, name='index'),
    url(r'^v1/list/$',views.listing_ajax, name='index_ajax'),
    #url(r'regist/$',views.regist,name='regist'),
    #url(r'login/$',views.login,name='login'),
    #url(r'logout/$',views.logout,name='logout'),
    url(r'^(?P<car_cate>[a-z]+)/$',views.listing, name='cate'),
    url(r'^(?P<car_id>\d+)/$',views.detail,name='detail'),
    url(r'^(?P<id>\d+)/commentshow/$', views.details_show_comment, name='showcomment'),

)

crawler/templates/car/car_detail.html
{% extends "base.html" %}
<!--{% load comments %}-->
{% block title %}{{ car.car_title }}{% endblock %}
<div class="article">
    {% block content %}
    <h1>{{ car.car_title }}</h1>
    <ul>
        {{ car.car_des }}
    </ul>
    <ul>
        {{ car.car_time }}
    </ul>
    <ul>
        {{ car.car_body|safe }}
    </ul>
    <div align="center">
        <a href="{{ car.car_link }}">源地址
            <!--{{ car.car_link }}-->
        </a>
    </div>
    <ul>
        from {{ car.car_source }}
    </ul>
    {% endblock %}

</div>

{% block comments %}
<article id="cmt">
    {% get_comment_count for car as comment_count %}
    <h4 class="muted comtop">{{ comment_count }} Comments</h4>
    <hr class="soften">
    {% get_comment_list for car as car_com %}
    {% for comment in car_com %}
    <div class="container-fluid none-padding">
        <p class="muted"><small>{{ comment.user }}</small><small>{{ comment.submit_date|date:"F,j,Y" }}</small></p>
        {{ comment.comment }}
    </div>
    <hr class="soften">
    {% endfor %}
</article>

<article >
    {% get_comment_form for car as car_form %}
    <div id="comment_form">
        <h4 class="muted comtop">New Comments</h4>
        <form class="form-horizontal" action="{% comment_form_target %}" method="post">
            <fieldset>
                {% csrf_token %}
                {{ car_form.object_pk }}
                {{ car_form.content_type }}
                {{ car_form.timestamp }}
                {{ car_form.site }}
                {{ car_form.submit_date }}
                {{ car_form.security_hash }}
                <div class="control-group">
                    <label class="control-label" for="id_comment">comment: </label>
                    <div class="controls">
                        <textarea class="input-xlarge comment" id="id_comment" name="comment" placeholder="please enter comment" required="required"></textarea>
                    </div>
                </div>
                <p style="display:none;"><label for="id_honeypot">如果你在该字段中输入任何内容，那么你的评论就会被视为垃圾评论。</label> <input type="text" name="honeypot" id="id_honeypot"></p>
                <div class="form-actions">
                    <input class="btn btn-info" id="id_submit" type="submit" name="submit" value="发表">
                    {# <input class="btn btn-info" type="submit" name="preview" value="Preview"> #}
                    <input type='hidden' name='next' value='{% url "spider:showcomment" car.id %}'/>
                </div>
            </fieldset>
        </form>
    </div>
</article>
{% endblock %}

{% block script %}
<script type="text/javascript" charset="utf-8">
function bindPostCommentHandler() {
//    $('#comment_form form input.submit-preview').remove();
    $('#comment_form form').submit(function() {
        $.ajax({
            type: "POST",
            data: $('#comment_form form').serialize(),
            url: "{% comment_form_target %}",
            cache: false,
            dataType: "html",
            success: function(html, textStatus) {
                $('#cmt').replaceWith(html);
                $('#comment_form form')[0].reset();
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                $('#comment_form form').replaceWith('Your comment was unable to be posted at this time.  We apologise for the inconvenience.');
            }
        });
        return false;
    });
}

$(document).ready(function() {
    bindPostCommentHandler();
});
</script>
{% endblock %}

crawler/templates/car/car_list.html
{% extends "base.html" %}
{% block title %}多可笑的清单{% endblock %}
{% block content %}

<ul class="thumbnails main-list">
    {% for i in car_list %}
    <li>
        <div class="thumbnail" style="overflow: hidden">
            <div class="span4" style="float: left;margin: 10px" >
                <a href="{% url 'spider:detail' i.id %}">
                    <img class="img-rounded listImg" src="{{ i.car_icon }}"/></a>

            </div>
            <div>
                <div class="caption" style="overflow: hidden">
                    <h3><a href="{% url 'spider:detail' i.id %}" class="text-warning">{{ i.car_title }}</a> </h3>
                </div>
                <p style="overflow: hidden">{{ i.car_des }}</p>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>

{% endblock %}
{% block website %}
<form action="" method="get" id="mysite" name="site">
    <div class="btn-group">
      <button type="submit" class="btn btn-default" id="chinaluxus">中奢网</button>
      <button type="submit" class="btn btn-default" id="527motor">527摩托</button>
      <button type="submit" class="btn btn-default" id="autohome">汽车之家</button>
      <!-- <button type="submit" class="btn btn-default" id="neeu">neeu</button> -->
      <input type="hidden" id="siteswitch" name="site" >
    </div>
</form>
<hr>
{% endblock %}
{% block script %}
<script src="/static/js/common.js"></script>
{% endblock %}

crawler/templates/car/car_list_ajax.html
{% for i in car_list %}
<li>
    <div class="thumbnail" style="overflow: hidden">
        <div class="span4" style="float: left;margin: 10px" >
            <a href="{% url 'spider:detail' i.id %}">
                <img class="img-rounded listImg" src="{{ i.car_icon }}"/></a>

        </div>
        <div>
            <div class="caption" style="overflow: hidden">
                <h3><a href="{% url 'spider:detail' i.id %}" class="text-warning">{{ i.car_title }}</a> </h3>
            </div>
            <p style="overflow: hidden">{{ i.car_des }}</p>
        </div>
    </div>
</li>
{% endfor %}

crawler/templates/car/details_comments_show.html
{% load comments %}
<article id="cmt">
    {% get_comment_count for details as comment_count %}
        <h4 class="muted comtop">{{ comment_count }} Comments</h4>
        <hr class="soften">  
    {% get_comment_list for details as blog_com %}
    {% for comment in blog_com %}
        <div class="container-fluid none-padding">
            <p class="muted"><small>{{ comment.user }}</small><small>{{ comment.submit_date|date:"F,j,Y" }}</small></p>      
            {{ comment.comment }}           
        </div>
        <hr class="soften">                   
    {% endfor %}
</article>

crawler/templates/car/login.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ lf.as_p }}
    <input type="submit" value="login"/>
</form>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %} > {{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
</body>
</html>

crawler/templates/car/logout.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <h3>Good bye </h3>
    {% if username %}
    <a href="/login/">login</a>
    {% endif %}
</body>
</html>

crawler/templates/car/regist.html
<!DOCTYPE html>
<html>
<head>
    <script src="/static/js/jquery.min.js"></script>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/static/css/bootstrap-responsive.min.css" rel="stylesheet" />
    <link href="/static/css/custom.css" rel="stylesheet" />
    <title></title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ rf.as_p }}
    <input type="submit" value="regist"/>
</form>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li> {% if message.tags %} class="{{ message.tags }}"{% endif %} > {{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
</body>
</html>

 